development:
  adapter: postgresql
  encoding: unicode
  database: itc_development
  pool: 5
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: itc_staging
  pool: 1
  timeout: 5000
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: itc_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: itc_production
  pool: 1
  timeout: 5000
  username: postgres
  password:
