production:
  pid_file: /u/apps/itc73/shared/tmp/searchd.pid
  searchd_file_path: /u/apps/itc73/shared/db/sphinx
  morphology: stem_ru
staging:
  pid_file: /u/apps/itc73/shared/tmp/searchd.pid
  searchd_file_path: /u/apps/itc73/shared/db/sphinx
  morphology: stem_ru
development:
  port: 9313
test:
  port: 9315